Foo::__construct
Caught exception!
===DONE===